name: Scrape Hentai Manga

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run scraper
      run: python scraper.py

    - name: Upload all manga zips
      uses: actions/upload-artifact@v4
      with:
        name: mangas
        path: output/
