name: Scrape Hentai Manga

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run scraper
      run: python scraper.py

    - name: Upload ZIP results
      uses: actions/upload-artifact@v4
      with:
        name: mangas
        path: output/*.zip
